# Generated by Django 5.1.4 on 2024-12-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241217_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
